package com.kh.example.chap01_exception.run;
import java.io.IOException;

import com.kh.example.chap01_exception.controller.ExceptionController;

public class Run {
	public static void main(String[] args) throws IOException {
		

		ExceptionController ec = new ExceptionController();
		try {
			ec.method1();
		}catch (IOException e) {
			e.printStackTrace();
		}
		System.out.println("정상적으로 종료됨...");
	}	
}
